# -*- coding: utf-8 -*-
"""RNN FOR MOVIE REVIEWS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CGpjCPcw72CmR5JUp3G-SmE3Sqn-rgAM
"""

from tensorflow.keras.datasets import imdb
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, Embedding

(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=10000)

x_train = pad_sequences(x_train, padding='post', maxlen=50)
x_test = pad_sequences(x_test, padding='post', maxlen=50)

print(x_train.shape)

model = Sequential()

model.add(Embedding(input_dim=10000, output_dim=32, input_length=50))
model.add(SimpleRNN(32))

model.add(Dense(1, activation='sigmoid'))

model.summary()

model.compile(
    optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])



history = model.fit(x_train, y_train, epochs=5,  validation_data=(x_test, y_test))

test_loss, test_acc = model.evaluate(x_test, y_test)

print("Test loss:", test_loss)
print("Test accuracy:", test_acc)